### PR TITLE
Update lockphish.sh

### PR DESCRIPTION
**Pull request by mrRA1**

### CODE REVIEW

**Comment by jaykali** [comment]
Just added a URL of YT video for promotion is not allowed. Sorry

**Comment by Gokul-Selva-105** [comment]
Url not gendrat

**Comment by jaykali** [comment]
I didn't maintain this repo. Please fix the errors and leave a PR. I will merge.

**Comment by jitesh-eng** [comment]
[+] Redirect after phishing (Default: Youtube ): 
[+] Downloading Ngrok...
[+] Starting php server...
[+] Starting ngrok server...                                                                                               
[+] Building webpages                                                                                                      
[+] Direct link: 

[*] Waiting targets, Press Ctrl + C to exit...


my link is not show in lockphish tool please  help

**Comment by jaykali** [comment]
> [+] Redirect after phishing (Default: Youtube ):
> [+] Downloading Ngrok...
> [+] Starting php server...
> [+] Starting ngrok server...
> [+] Building webpages
> [+] Direct link:
> 
> [*] Waiting targets, Press Ctrl + C to exit...
> 
> my link is not show in lockphish tool please help

This tool is not maintained.

**Comment by jitesh-eng** [comment]
> > [+] Redirect after phishing (Default: Youtube ):
> > [+] Downloading Ngrok...
> > [+] Starting php server...
> > [+] Starting ngrok server...
> > [+] Building webpages
> > [+] Direct link:
> > [*] Waiting targets, Press Ctrl + C to exit...
> > my link is not show in lockphish tool please help
> 
> This tool is not maintained.



> > [+] Redirect after phishing (Default: Youtube ):
> > [+] Downloading Ngrok...
> > [+] Starting php server...
> > [+] Starting ngrok server...
> > [+] Building webpages
> > [+] Direct link:
> > [*] Waiting targets, Press Ctrl + C to exit...
> > my link is not show in lockphish tool please help
> 
> This tool is not maintained.

how to maintain it ???

**Comment by jaykali** [comment]
> > > [+] Redirect after phishing (Default: Youtube ):
> > > [+] Downloading Ngrok...
> > > [+] Starting php server...
> > > [+] Starting ngrok server...
> > > [+] Building webpages
> > > [+] Direct link:
> > > [*] Waiting targets, Press Ctrl + C to exit...
> > > my link is not show in lockphish tool please help
> > 
> > 
> > This tool is not maintained.
> 
> > > [+] Redirect after phishing (Default: Youtube ):
> > > [+] Downloading Ngrok...
> > > [+] Starting php server...
> > > [+] Starting ngrok server...
> > > [+] Building webpages
> > > [+] Direct link:
> > > [*] Waiting targets, Press Ctrl + C to exit...
> > > my link is not show in lockphish tool please help
> > 
> > 
> > This tool is not maintained.
> 
> how to maintain it ???

Need solve the problems Lockphish getting. Then open a Pull request on it's Github repo. We will marge it, and you will be a contributor of this tool. 

You need to have good knowledge on bash scripting to fix all the errors in lockphish tool

**Pull request closed without merging**
